[package]
name = "rust-elf-parser"
version = "0.1.0"
authors = ["akatsuki-py <bluejapan73+dev@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
